name: Environments test

on:
  # push:
  #   branches:
  #     - main

  repository_dispatch:
    types: [custom-event]

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Run fake build
        run: npm run build

      - name: Completion
        run: echo "Hello ${{ github.actor }}. You pushed to ${{ github.repository }} at $(date)."

  dev_deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Completion
        run: echo "Fake deploy to dev."
      - name: Echo secret
        run: echo "${{ secrets.CITY }}"
      - name: Echo env
        run: echo "${{ env.COUNTRY }}"

  prod_deploy:
    runs-on: ubuntu-latest
    needs: [dev_deploy]
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Completion
        run: echo "Fake deploy to prod."
      - name: Echo secret
        run: echo "${{ secrets.CITY }}"
      - name: Echo env
        run: echo "${{ env.COUNTRY }}"
